server:
  port: 8081
  servlet:
   context-path: "/companyinfo"
   

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/infocompany
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
     
     